FROM golang:1.17.0-alpine

COPY . /go/src/github.com/dirkarnez/golang-hello-world
WORKDIR /go/src/github.com/dirkarnez/golang-hello-world

RUN go get .
RUN go get -u github.com/dirkarnez/again@master

EXPOSE 9000

ENTRYPOINT ["again","run"]